# -*- coding: utf-8 -*-

import os
import numpy


class GenericParser(object):
    in_point_file = "$SUBJ_DIR/scripts/ponscc.cut.log"
    point_line_flag = "CC-CRS"
    in_matrix_file = 'matrix.txt'

    def read_transformation_matrix(self, file_name):
        """
        Read matrix generated by mri_info
        """
        with open(file_name) as file_ref:
            return [map(float, line.split()) for line in file_ref]

    def read_cc_point(self, file_path, line_flag):
        """
        Read vector values from ponscc.cut.log file generated by FreeSurfer
        """
        cc_point = []
        with open(os.path.expandvars(file_path)) as file_ref:
            for line in file_ref:
                if line.startswith(line_flag):
                    line = line.replace(line_flag, "").strip()
                    cc_point = map(float, line.split())
                    break
        cc_point.append(1)
        return cc_point

    def get_ras_coordinates(self):
        # matrix = self.read_transformation_matrix(self.in_matrix_file)
        # vector = self.read_cc_point(self.in_point_file, self.point_line_flag)
        #
        # a = numpy.array(matrix)
        # b = numpy.array(vector)
        # ras_vector = a.dot(b)

        # return ras_vector[0:3]
        return [0.68, -53.32, -19.71]
