# -*- coding: utf-8 -*-

import os
import numpy
from bnm.recon.qc.model.constants import CC_POINT_FILE


class GenericIO(object):
    point_line_flag = "CC-CRS"

    def read_cc_point(self, file_path, line_flag):
        """
        Read vector values from ponscc.cut.log file generated by FreeSurfer
        """
        cc_point = []
        with open(os.path.expandvars(file_path)) as file_ref:
            for line in file_ref:
                if line.startswith(line_flag):
                    line = line.replace(line_flag, "").strip()
                    cc_point = map(float, line.split())
                    break
        cc_point.append(1)
        return cc_point

    def get_ras_coordinates(self, matrix):
        vector = self.read_cc_point(CC_POINT_FILE, self.point_line_flag)

        a = numpy.array(matrix)
        b = numpy.array(vector)
        ras_vector = a.dot(b)

        return ras_vector[0:3]
